#!/usr/bin/env bash
# After configuring domain zone, use this script to output where each subdomain points to

runDig () {
    Subarg=$1
    Urlarg=$2

    dig "$Subarg.$Urlarg" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v s="$Subarg" 'BEGIN { FS = " " } ; { print "The subdomain " s " is a " $4 " record and points to " $5 }'
}

AllSubs=( "www" "lb-01" "web-01" "web-02" )

if [ $# -eq 1 ]; then
    Url="$1"
    for s in "${AllSubs[@]}"
    do
		runDig "$s" "$Url"
    done
elif [ $# -eq 2 ]; then
	url="$1"
    sub="$2"
	runDig "$Sub" "$Url"
fi
